GET http://localhost:8080/api/nodes/active

###

POST http://localhost:8080/api/nodes/active/login
Content-Type: application/json

{
  "id": 24,
  "password": "123",
  "serverPort": 41959,
  "clientPort": 55004
}

###

POST http://localhost:8080/api/nodes/active/logout
Content-Type: application/json

{
  "id": 24,
  "password": "123",
  "serverPort": 41956,
  "clientPort": 55001
}

###

POST http://localhost:8080/api/nodes/register
Content-Type: application/json

{
  "password": "123"
}
