GET http://localhost:8080/api/nodes/active

###

POST http://localhost:8080/api/nodes/active/login
Content-Type: application/json

{
  "id": 3,
  "password": "abcd",
  "syncport": 41953,
  "clientport": 55006
}

###

POST http://localhost:8080/api/nodes/active/logout
Content-Type: application/json

{
  "id": 2,
  "password": "abcd"
}

###

POST http://localhost:8080/api/nodes/register
Content-Type: application/json

{
  "password": 123
}
